workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk